In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
%cd /content/drive/My Drive/Colab Notebooks/

/content/drive/My Drive/Colab Notebooks

In [ ]:
import pandas as pd
df = pd.read_excel("final_pre-ml.xlsx")

In [ ]:
df.head()

,Unnamed: 0,date,Tweet,Close,Tweet.1,tidy text,Vader Scores,Vader Compound Score,Textblob Score,Plutchik,EmoLex Score,Anger,Anticipation,Disgust,Fear,Joy,Sadness,Surprise,Trust
0,0,2022-12-30,"Reliance Buys 51% Stake In Lotus Chocolate, Up...",2547.20,"Reliance Buys 51% Stake In Lotus Chocolate, Up...",Reliance Buys Stake In Lotus Chocolate Up...,"{'neg': 0.034, 'neu': 0.884, 'pos': 0.082, 'co...",0.9996,0.127198,"{'anger': 0.007792713812585233, 'anticipation'...",0.019482,0.007793,0.016170,0.002922,0.005650,0.010325,0.002727,0.002922,0.022014
1,1,2022-12-29,#Reliance The Name IS Enough: RIL is taking ni...,2543.30,#Reliance The Name IS Enough: RIL is taking ni...,#Reliance The Name IS Enough RIL is taking ni...,"{'neg': 0.023, 'neu': 0.895, 'pos': 0.082, 'co...",0.9997,0.113736,"{'anger': 0.004760919064375905, 'anticipation'...",0.019872,0.004761,0.014076,0.001863,0.002691,0.009729,0.001035,0.003312,0.020493
2,2,2022-12-28,Commodity Market| 28thNOV22\n\n#GOLDðŸ‘‰TARGET\n\...,2544.45,Commodity Market| 28thNOV22\n\n#GOLDðŸ‘‰TARGET\n\...,Commodity Market thNOV #GOLD TARGET #BA...,"{'neg': 0.015, 'neu': 0.887, 'pos': 0.098, 'co...",0.9998,0.170223,"{'anger': 0.002718622564567286, 'anticipation'...",0.018804,0.002719,0.014952,0.001812,0.005211,0.010421,0.001359,0.002719,0.022202
3,3,2022-12-27,"BIRTHDAY ANAGRAM QUESTION # 7:\n""AT AN ATTAR"" ...",2544.70,"BIRTHDAY ANAGRAM QUESTION # 7:\n""AT AN ATTAR"" ...",BIRTHDAY ANAGRAM QUESTION # AT AN ATTAR ...,"{'neg': 0.031, 'neu': 0.855, 'pos': 0.113, 'co...",0.9997,0.108293,"{'anger': 0.005555555555555556, 'anticipation'...",0.028947,0.005556,0.021053,0.000877,0.003801,0.011696,0.001462,0.003801,0.031579
4,4,2022-12-26,#RelianceIndustries $RELIANCE Weekly Chart\n#S...,2524.05,#RelianceIndustries $RELIANCE Weekly Chart\n#S...,#RelianceIndustries RELIANCE Weekly Chart #Su...,"{'neg': 0.024, 'neu': 0.894, 'pos': 0.083, 'co...",0.9993,0.135712,"{'anger': 0.006431767337807606, 'anticipation'...",0.013423,0.006432,0.015660,0.000559,0.006991,0.006711,0.002237,0.003356,0.032998

In [ ]:
df.columns

Index(['Unnamed: 0', 'date', 'Tweet', 'Close', 'Tweet.1', 'tidy text',
       'Vader Scores', 'Vader Compound Score', 'Textblob Score', 'Plutchik',
       'EmoLex Score', 'Anger', 'Anticipation', 'Disgust', 'Fear', 'Joy',
       'Sadness', 'Surprise', 'Trust'],
      dtype='object')

In [ ]:
#subsetting necessary columns from the original Dataframe

df_var= df[["Vader Compound Score","Textblob Score","EmoLex Score", 'Anger', 'Anticipation', 'Disgust', 'Fear', 'Joy', 'Sadness', 'Surprise', 'Trust']]

In [ ]:
df_var

,Vader Compound Score,Textblob Score,EmoLex Score,Anger,Anticipation,Disgust,Fear,Joy,Sadness,Surprise,Trust
0,0.9996,0.127198,0.019482,0.007793,0.016170,0.002922,0.005650,0.010325,0.002727,0.002922,0.022014
1,0.9997,0.113736,0.019872,0.004761,0.014076,0.001863,0.002691,0.009729,0.001035,0.003312,0.020493
2,0.9998,0.170223,0.018804,0.002719,0.014952,0.001812,0.005211,0.010421,0.001359,0.002719,0.022202
3,0.9997,0.108293,0.028947,0.005556,0.021053,0.000877,0.003801,0.011696,0.001462,0.003801,0.031579
4,0.9993,0.135712,0.013423,0.006432,0.015660,0.000559,0.006991,0.006711,0.002237,0.003356,0.032998
...,...,...,...,...,...,...,...,...,...,...,...
243,0.9998,0.149203,0.018100,0.002765,0.018854,0.001257,0.002765,0.012821,0.003268,0.004274,0.018100
244,0.9989,0.084713,0.008435,0.002942,0.013927,0.000588,0.002158,0.006081,0.003531,0.005885,0.011965
245,0.9996,0.145476,0.029833,0.004773,0.027446,0.001193,0.006762,0.017502,0.004773,0.006364,0.026253
246,0.9994,0.107530,0.015582,0.007027,0.025053,0.001833,0.010082,0.011916,0.005500,0.007333,0.025970
247,0.9978,0.128041,0.010772,0.008528,0.025135,0.002244,0.009425,0.011670,0.008079,0.007630,0.021095

In [ ]:
#Importing the necessary libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#Scaling the data using StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled=pd.DataFrame(scaler.fit_transform(df_var),columns=df_var.columns)

In [ ]:
df_scaled

,Vader Compound Score,Textblob Score,EmoLex Score,Anger,Anticipation,Disgust,Fear,Joy,Sadness,Surprise,Trust
0,0.088399,1.022355,0.487164,0.844408,-0.798458,0.255633,-0.292855,0.251961,-1.031202,-1.023091,-0.677643
1,0.090319,0.629112,0.559216,-0.612366,-1.267832,-0.513086,-1.644073,0.061786,-1.768730,-0.828423,-1.028144
2,0.092239,2.279186,0.361870,-1.593687,-1.071337,-0.549772,-0.493350,0.282580,-1.627397,-1.124825,-0.634418
3,0.090319,0.470118,2.236458,-0.230544,0.295957,-1.228450,-1.137056,0.688913,-1.582653,-0.584024,1.525313
4,0.082638,1.271067,-0.632567,0.190474,-0.912752,-1.459153,0.319710,-0.900207,-1.244866,-0.806562,1.852103
...,...,...,...,...,...,...,...,...,...,...,...
243,0.092239,1.665159,0.231719,-1.571303,-0.196910,-0.952893,-1.610162,1.047452,-0.795657,-0.348063,-1.579337
244,0.074958,-0.218693,-1.554404,-1.486196,-1.301168,-1.437976,-1.887597,-1.101248,-0.681127,0.456812,-2.992170
245,0.088399,1.556297,2.400115,-0.606432,1.729028,-0.999043,0.215166,2.539966,-0.139693,0.696452,0.298608
246,0.084559,0.447832,-0.233532,0.476575,1.192701,-0.534703,1.731519,0.758978,0.176795,1.180210,0.233443
247,0.053835,1.046979,-1.122455,1.197629,1.210897,-0.236457,1.431478,0.680545,1.300845,1.328800,-0.889372

In [ ]:
#import stats models
#Splitting the data into train and test
from statsmodels import api as sm
from sklearn.model_selection import train_test_split

X = df_scaled
X = sm.add_constant(X)
y = df["Close"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
#OLS Model fitting for the train data

model = sm.OLS(y_train,X_train).fit()

In [ ]:
model.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                      Results: Ordinary least squares
===========================================================================
Model:                 OLS                 Adj. R-squared:        0.073
Dependent Variable:    Close               AIC:                   2454.3776
Date:                  2023-01-09 11:31    BIC:                   2493.8368
No. Observations:      198                 Log-Likelihood:        -1215.2
Df Model:              11                  F-statistic:           2.401
Df Residuals:          186                 Prob (F-statistic):    0.00828
R-squared:             0.124               Scale:                 13350.
---------------------------------------------------------------------------
                       Coef.   Std.Err.    t     P>|t|    [0.025    0.975]
---------------------------------------------------------------------------
const                2533.4829   8.2431 307.3444 0.0000 2517.2208 2549.7449
Vader Compound Score   10.6003   7.4494   1.4230 0.1564   -4.0958   25.2964
Textblob Score         23.7126   9.3788   2.5283 0.0123    5.2101   42.2152
EmoLex Score          -18.0853  12.5698  -1.4388 0.1519  -42.8831    6.7124
Anger                  37.6178  13.5539   2.7754 0.0061   10.8787   64.3569
Anticipation          -16.9495  11.8810  -1.4266 0.1554  -40.3883    6.4892
Disgust                14.3317  10.6900   1.3407 0.1817   -6.7576   35.4209
Fear                  -28.4184  10.9567  -2.5937 0.0103  -50.0338   -6.8029
Joy                     8.3547  12.3637   0.6757 0.5000  -16.0364   32.7458
Sadness               -18.9008  12.5656  -1.5042 0.1342  -43.6903    5.8887
Surprise                8.0912  11.1393   0.7264 0.4685  -13.8845   30.0668
Trust                   2.9081   9.3856   0.3098 0.7570  -15.6079   21.4241
---------------------------------------------------------------------------
Omnibus:                  4.126           Durbin-Watson:              2.061
Prob(Omnibus):            0.127           Jarque-Bera (JB):           3.033
Skew:                     0.160           Prob(JB):                   0.219
Kurtosis:                 2.485           Condition No.:              4
===========================================================================

"""

In [ ]:
#Subsetting the features - Anger, Fear, Textblob.
df_train_final1=df_scaled[['Textblob Score','Anger','Fear']]

In [ ]:
#OLS Model on the Test data

import statsmodels.api as sm
X1= sm.add_constant(df_train_final1)
ols=sm.OLS(y,X1)
result=ols.fit()
result.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                   Results: Ordinary least squares
=====================================================================
Model:               OLS               Adj. R-squared:      0.047
Dependent Variable:  Close             AIC:                 3071.4886
Date:                2023-01-09 11:36  BIC:                 3085.5423
No. Observations:    248               Log-Likelihood:      -1531.7
Df Model:            3                 F-statistic:         5.041
Df Residuals:        244               Prob (F-statistic):  0.00209
R-squared:           0.058             Scale:               13783.
---------------------------------------------------------------------
                 Coef.   Std.Err.    t     P>|t|    [0.025    0.975]
---------------------------------------------------------------------
const          2528.7899   7.4549 339.2138 0.0000 2514.1058 2543.4740
Textblob Score   15.9194   7.5169   2.1178 0.0352    1.1131   30.7258
Anger            32.4767   9.8523   3.2964 0.0011   13.0703   51.8831
Fear            -28.4006   9.7909  -2.9007 0.0041  -47.6860   -9.1151
---------------------------------------------------------------------
Omnibus:               10.375         Durbin-Watson:            0.194
Prob(Omnibus):         0.006          Jarque-Bera (JB):         4.883
Skew:                  -0.030         Prob(JB):                 0.087
Kurtosis:              2.315          Condition No.:            2
=====================================================================

"""

In [ ]:
#Predicting the Stock Price using the OLS Model on the Test data

y_pred = model.predict(X_test)
y_pred

108    2435.339135
237    2522.206553
16     2485.843940
132    2617.787758
6      2529.300214
123    2507.869202
34     2550.557489
37     2496.707483
49     2600.985197
83     2532.685971
9      2536.925448
208    2482.162370
125    2565.779292
41     2550.861007
0      2618.483450
199    2557.254050
230    2498.712575
8      2548.264626
27     2537.805182
89     2507.871706
245    2485.730024
73     2563.035114
148    2511.941034
91     2540.627237
57     2590.972970
39     2520.779937
55     2518.944267
87     2515.322343
120    2542.506214
216    2530.395399
65     2567.449278
126    2567.727456
188    2503.798637
210    2520.831533
197    2574.210612
18     2603.424449
231    2594.580858
218    2462.264331
106    2499.698870
220    2597.899572
3      2541.539036
173    2648.018027
40     2623.247908
115    2451.148571
204    2491.888890
32     2565.843909
150    2555.329102
104    2471.391047
74     2575.426778
166    2550.778204
dtype: float64

In [ ]:
#Predicting the Stock Price using the OLS Model on the Training data

y_pred1 = model.predict(X_train)
y_pred1

111    2524.477235
138    2520.205353
159    2523.609718
127    2538.773285
23     2557.270959
          ...
229    2481.233830
42     2580.348748
43     2531.490466
143    2597.731910
209    2537.461377
Length: 198, dtype: float64

In [ ]:
from sklearn import metrics
from sklearn.metrics import r2_score

In [ ]:
#Defining the variables for performance metrics - OLS Model

e1 = metrics.mean_absolute_error(y_test,y_pred)
e2 = np.mean(np.abs((y_test- y_pred)/y_test))*100
e3 = metrics.mean_squared_error(y_test, y_pred)
e4 = np.sqrt(metrics.mean_squared_error(y_test, y_pred))

In [ ]:
#creating a list for the evaluation metrics 

errors=['MAE','MAPE', 'MSE', 'RMSE']
values=[e1,e2,e3,e4]

In [ ]:
error = pd.DataFrame({'Errors' :errors, 'Values': values})
error

  Errors        Values
0    MAE     96.021281
1   MAPE      3.890196
2    MSE  13853.304486
3   RMSE    117.700062

Regularized regression Model

In [ ]:
# importing the Ridge model 

from sklearn.linear_model import Ridge

## training the model using Ridge 

ridgeReg = Ridge(alpha=0.05, normalize=True)

ridgeReg.fit(X_train,y_train)

pred = ridgeReg.predict(X_test)

In [ ]:
#Defining the variables for performance metrics - Regularized Regression Model

from sklearn import metrics
from sklearn.metrics import r2_score

ri1 = metrics.mean_absolute_error(y_test,pred)
ri2 = np.mean(np.abs(y_test- pred)/y_test)*100
ri3 = metrics.mean_squared_error(y_test, pred)
ri4 = np.sqrt(metrics.mean_squared_error(y_test, pred))

In [ ]:
values1=[ri1,ri2,ri3,ri4]
error = pd.DataFrame({'Errors' :errors, 'LR Metrics': values, 'Ridge Metrics': values1})

error

  Errors    LR Metrics  Ridge Metrics
0    MAE     96.021281      96.188144
1   MAPE      3.890196       3.897229
2    MSE  13853.304486   13746.804006
3   RMSE    117.700062     117.246765

LassoRegression Model

In [ ]:
#importing and training the data using LassoRegression Model 

from sklearn.linear_model import Lasso

lassoReg = Lasso(alpha=0.3, normalize=True)

lassoReg.fit(X_train,y_train)

pred1 = lassoReg.predict(X_test)

In [ ]:
#Defining the variables for performance metrics - Lasso Regression Model

from sklearn import metrics
from sklearn.metrics import r2_score

la1 = metrics.mean_absolute_error(y_test,pred1)
la2 = np.mean(np.abs(y_test- pred1)/y_test)*100
la3 = metrics.mean_squared_error(y_test, pred1)
la4 = np.sqrt(metrics.mean_squared_error(y_test, pred1))

In [ ]:
values2=[la1,la2,la3,la4]
error = pd.DataFrame({'Errors' :errors, 'LR Metrics': values, 'Ridge Metrics': values1, 'Lasso Metrics': values2})

error

  Errors    LR Metrics  Ridge Metrics  Lasso Metrics
0    MAE     96.021281      96.188144      98.572887
1   MAPE      3.890196       3.897229       3.995676
2    MSE  13853.304486   13746.804006   14106.368490
3   RMSE    117.700062     117.246765     118.770234

In [ ]:
### FITTING A RANDOM FOREST REGRESSOR 
# import the regressor
from sklearn.ensemble import RandomForestRegressor
 
 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
 
# fit the regressor with x and y data
rf= regressor.fit(X_train, y_train)
y_pred2 = rf.predict(X_test)

In [ ]:
#Defining the variables for performance metrics - Random Forest Model

r1 = metrics.mean_absolute_error(y_test,y_pred2)
r2 = np.mean(np.abs(y_test- y_pred2)/y_test)*100
r3= metrics.mean_squared_error(y_test, y_pred2)
r4 = np.sqrt(metrics.mean_squared_error(y_test, y_pred2))
r5 = r2_score(y_test, y_pred2)

In [ ]:
metrics=['MAE','MAPE', 'MSE', 'RMSE']
values3=[r1,r2,r3,r4]

In [ ]:
error = pd.DataFrame({'Errors' :errors, 'LR Metrics': values, 'Ridge Metrics': values1, 'Lasso Metrics': values2, 'RF Metrics': values3})

error

  Errors    LR Metrics  Ridge Metrics  Lasso Metrics    RF Metrics
0    MAE     96.021281      96.188144      98.572887    103.353890
1   MAPE      3.890196       3.897229       3.995676      4.165665
2    MSE  13853.304486   13746.804006   14106.368490  15223.812303
3   RMSE    117.700062     117.246765     118.770234    123.384814